### Listar todos os gêneros
GET http://localhost:3001/generos

### Buscar gênero por ID
GET http://localhost:3001/generos/1

### Cadastrar novo gênero
POST http://localhost:3001/generos
Content-Type: application/json

{
    "nome": "Ação"
}

### Atualizar gênero
PUT http://localhost:3001/generos/1
Content-Type: application/json

{
    "nome": "Ação e Aventura"
}

### Remover gênero
DELETE http://localhost:3001/generos/1
