### Listar todas as plataformas
GET http://localhost:3001/plataformas

### Buscar plataforma por ID
GET http://localhost:3001/plataformas/1

### Cadastrar nova plataforma
POST http://localhost:3001/plataformas
Content-Type: application/json

{
    "nome": "PC"
}

### Cadastrar outra plataforma
POST http://localhost:3001/plataformas
Content-Type: application/json

{
    "nome": "PlayStation 5"
}

### Atualizar plataforma
PUT http://localhost:3001/plataformas/1
Content-Type: application/json

{
    "nome": "Steam / PC"
}

### Remover plataforma
DELETE http://localhost:3001/plataformas/1
